version: '3'
services:
  frontend:
    container_name: 'malwarebytes-frontend'
    stdin_open: true
    build:
      context: .
      dockerfile: docker/dev/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./:/src